#!/usr/bin/env python

#################################################################
# print the programs that are in error.txt and not in any other #
#################################################################

from whylib import strings, counters, outfiles_names, open_outfiles, close_outfiles

outfiles = open_outfiles(outfiles_names, 'r')

program = outfiles['ERROR'].readline()

while program:
	if (program not in outfiles['EXIT STATUS'].read()):
		print program,
	program = outfiles['ERROR'].readline()

close_outfiles(outfiles)
