#!/usr/bin/env python

from gzip import open
from whylib import *

# (open_outfiles returns a dict)
outfiles = open_outfiles(outfiles_names, 'w')

for mandir in mandirs:

	# right now, programs list holds all the programs that
	# their manpages live in man 1 section (sorted per manpath)

	# iterate over every program with a manpage in
	# current mandir and search for the strings

	programs = all_progs[mandir]
	n = len(programs)
	i = 1

	for program in programs:

		print "[-] Now processing manpage file (%d/%d) from %s : %s ..." % (i, n, mandir, program)

		with open(mandir + program, "r") as manpage:
			manfile = manpage.read()
			for string in strings:
				if string in manfile:
					print "[!] String \"%s\" found in manpage file : %s" % (string, program)
					print "[!] The name of the manpage file will be logged in file : %s" % outfiles_names[string]
					data_to_write = "(" + mandir + ") " + program + '\n'
					outfiles[string].write(data_to_write)
					counters[string] += 1

		i += 1

	print "[!] Done."

close_outfiles(outfiles)

# finally
print "[!] Done for all manual directories."
print "[!] --------------------------------"
print "[!] Statistics:"
for string in counters:
	print "[!] \"%s\" found %d times." % (string, counters[string])
